package tests.ozan;

import com.github.javafaker.Faker;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.Select;
import org.testng.Assert;
import org.testng.annotations.Test;
import pages.HomePage;
import utilities.*;

import javax.swing.*;
import java.awt.*;
import java.awt.datatransfer.StringSelection;
import java.awt.event.KeyEvent;
import java.util.List;

public class US09_TC01 extends TestBaseRapor {
    HomePage homePage = new HomePage();
    Faker faker = new Faker();

    Actions action = new Actions(Driver.getDriver());
    Robot robot = new Robot();

    public US09_TC01() throws AWTException {
    }
    @Test
    public void test01() {
        extentTest = extentReports.createTest("Olusturulmuş Vcard düzenleme testi", "Kullanıcı var olan Vcardını düzenleyebilmelidir.");
        extentTest.info("Tarayıcı açılır ana sayfaya gidilir.");
        Driver.getDriver().get(ConfigReader.getProperty("smartCardLinkUrl"));
        extentTest.info("Sign In butonuna tıklar.");
        homePage.signInButton.click();
        extentTest.info("Kullanıcı username ve password ile login olur");
        homePage.emailtextBox.sendKeys(ConfigReader.getProperty("scGecerliEmail"));
        homePage.passwordTextBox.sendKeys(ConfigReader.getProperty("scGecerliPassword"));
        homePage.loginButonu.click();
        extentTest.info("Kullanıcı Dasboard bölümünde VCard butonuna tıklar");
        homePage.vcardButton.click();
        ReusableMethods.wait(1);
        extentTest.info("Kullanıcı edit butonuna tıklayarak düzenleme sayfasını açar.");
        homePage.editButtonOK.click();
        extentTest.info("Kullanıcı Basic Details bölümünü istenen formatta doldurur.");
        homePage.urlGenerateButton.click();
        homePage.vcardNameTextbox.clear();
        homePage.vcardNameTextbox.sendKeys(faker.name().fullName());
        homePage.occupationOK.clear();
        homePage.occupationOK.sendKeys(faker.job().title());
        homePage.descriptionOK.clear();
        homePage.descriptionOK.sendKeys(faker.address().country());
        JSUtilities.scrollToElement(Driver.getDriver(), homePage.vcardDetailsText);
        homePage.firstNameTextBoxOK.clear();
        homePage.firstNameTextBoxOK.sendKeys(faker.name().firstName());
        homePage.lastNameTextBoxOK.clear();
        homePage.lastNameTextBoxOK.sendKeys(faker.name().lastName());
        homePage.emailTextBoxOK.clear();
        homePage.emailTextBoxOK.sendKeys(faker.internet().emailAddress());
        homePage.phoneNumberTextBoxOK.clear();
        homePage.phoneNumberTextBoxOK.sendKeys(faker.phoneNumber().cellPhone());
        homePage.locationTextBoxOK.clear();
        homePage.locationTextBoxOK.sendKeys(faker.address().cityName());
        homePage.dateOfBirthTextBoxOK.clear();
        homePage.dateOfBirthTextBoxOK.sendKeys("18/02/1991");
        homePage.companyTextBoxOK.clear();
        homePage.companyTextBoxOK.sendKeys(faker.company().name());
        homePage.jobTitleTextBoxOK.clear();
        homePage.jobTitleTextBoxOK.sendKeys(faker.job().title());
        homePage.defaultLanguageBoxOK.click();
        homePage.defaultLanguageTextBoxOK.sendKeys("Turkish" + Keys.ENTER);
        JSUtilities.scrollToElement(Driver.getDriver(), homePage.emailTextBoxOK);
        action.dragAndDrop(homePage.qrCodeDownloadSize, homePage.emailTextBoxOK);
        homePage.saveButtonOK.click();
        Assert.assertTrue(homePage.basicBildirim.isDisplayed(), "Save yapıldıktan sonra başarılı bildirimi alınmıyor");
        extentTest.pass("Kullanıcı Basic Details bölümünü başarılı bir şekilde doldurup save yaptı");
        JSUtilities.scrollToElement(Driver.getDriver(), homePage.urlGenerateButton);
        extentTest.info("Kullanıcı VCard Templates butonuna tıklar ve bir template seçip kayıt yapar.");
        homePage.vcardTemplatesButtonOK.click();
        homePage.templateOK2.click();
        JSUtilities.scrollToElement(Driver.getDriver(), homePage.basicDetailsOK);
        homePage.templatesSaveButton.click();
        Assert.assertTrue(homePage.basicBildirim.isDisplayed(), "Save yapıldıktan sonra başarılı bildirimi alınmıyor");
        extentTest.pass("Kullanıcı template seçip save eder.");
        extentTest.info("Kullanıcı Business Hours butonuna tıklar gün ve saat kaydı oluşturur");
        homePage.businessHoursButton.click();
        homePage.mondayOK.click();
        homePage.hoursSelectOK.click();
        ReusableMethods.wait(1);
        homePage.hoursSelectTextbox.sendKeys("9" + Keys.ENTER);
        homePage.businessSaveButtonOK.click();
        Assert.assertTrue(homePage.basicBildirim.isDisplayed(), "Save yapıldıktan sonra başarılı bildirimi alınmıyor");
        extentTest.pass("Kullanıcı olusturdugu gün ve tarihi başarılı bir şekilde save eder.");
        extentTest.info("Kullanıcı Services butonuna tıklar.");
        homePage.servicesButton.click();
        extentTest.info("Add Service butonuna tıklayıp bilgileri girerek service oluşturur ve save eder.");
        homePage.addServiceButton.click();
        homePage.serviceNameTextBox.sendKeys("IT");
        homePage.serviceUrl.sendKeys("https://www.amazon.com.tr");
        homePage.descriptionAddServiceOK.sendKeys("deneme1");
        homePage.servicesUploadButton.click();
        ReusableMethods.wait(1);
        StringSelection stringSelection = new StringSelection("C:\\Users\\Ozan\\pexels-photo-1692984.jpeg"); // Resmin dosya yolunu buraya ekleyin
        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(stringSelection, null);
        robot.keyPress(KeyEvent.VK_CONTROL);
        robot.keyPress(KeyEvent.VK_V);
        robot.keyRelease(KeyEvent.VK_CONTROL);
        robot.keyRelease(KeyEvent.VK_V);
        robot.keyPress(KeyEvent.VK_ENTER);
        robot.keyRelease(KeyEvent.VK_ENTER);
        ReusableMethods.wait(2);
        JSUtilities.scrollToElement(Driver.getDriver(),homePage.serviesNameText);
        homePage.serviceSaveButton.click();
        extentTest.pass("Service sekmesine başarıyla yeni bir servis girildi.");
        extentTest.info("Kullanıcı Testimonials butonuna tıklar.");
        ReusableMethods.wait(2);
        homePage.testimonialsButton.click();
        homePage.addTestimonialButton.click();
        ReusableMethods.wait(2);
        homePage.nameTestimonial.sendKeys(faker.funnyName().name());
        homePage.descriptionTestimonial.clear();
        homePage.descriptionTestimonial.sendKeys(faker.funnyName().name());
        homePage.testimonialUploadButton.click();
        ReusableMethods.wait(1);
        StringSelection stringSelection1 = new StringSelection("C:\\Users\\Ozan\\pexels-photo-1692984.jpeg"); // Resmin dosya yolunu buraya ekleyin
        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(stringSelection1, null);
        ReusableMethods.wait(1);
        robot.keyPress(KeyEvent.VK_CONTROL);
        robot.keyPress(KeyEvent.VK_V);
        robot.keyRelease(KeyEvent.VK_CONTROL);
        robot.keyRelease(KeyEvent.VK_V);
        robot.keyPress(KeyEvent.VK_ENTER);
        robot.keyRelease(KeyEvent.VK_ENTER);
        ReusableMethods.wait(2);
        homePage.testimonialSaveButton.click();
        extentTest.pass("kullanıcı başarıyla testimonial oluşturur.");
        extentTest.info("Kullanıcı Socials Links-Website butonuna tıklar");
        extentTest.info("Textboxları doldurur.");
        ReusableMethods.wait(1);
        homePage.socialLinksButton.click();
        homePage.youtubeTextbox.clear();
        homePage.youtubeTextbox.sendKeys("https://www.youtube.com");
        homePage.twitterTextBox.clear();
        homePage.twitterTextBox.sendKeys("https://www.twitter.com");
        homePage.linkedinTextBox.clear();
        homePage.linkedinTextBox.sendKeys("https://www.linkedin.com");
        homePage.socialSaveButton.click();
        Assert.assertTrue(homePage.basicBildirim.isDisplayed(), "Save yapıldıktan sonra başarılı bildirimi alınmıyor");
        extentTest.pass("Kullanıcı sosyal hesaplarını başarılı bir şekilde kayıt eder.");
        extentTest.info("Kullanıcı Fonts butonuna tıklar");
        homePage.fontsButton.click();
        extentTest.info("Kullanıcı font seçip boyut ayarlar.");
        homePage.fontFamilyDropDown.click();
        homePage.fontFamilTextBox.sendKeys("Roboto" + Keys.ENTER);
        homePage.frontSizeTextBox.clear();
        homePage.frontSizeTextBox.sendKeys("20");
        homePage.fontsSaveButton.click();
        Assert.assertTrue(homePage.basicBildirim.isDisplayed(), "Save yapıldıktan sonra başarılı bildirimi alınmıyor");
        extentTest.pass("Kullanıcı seçtiği fontu başarıyla kayıt eder.");
        extentTest.info("Kullanıcı Privacy Policy butonuna tıklayıp textboxı doldurup save eder.");
        JSUtilities.scrollToElement(Driver.getDriver(), homePage.vcardTemplatesButtonOK);
        ReusableMethods.wait(1);
        homePage.privacyPolicyButton.click();
        ReusableMethods.wait(1);
        homePage.privacyPolicyTextbox.sendKeys("Gizlilik Politikası");
        homePage.privacySaveButton.click();
        Assert.assertTrue(homePage.basicBildirim.isDisplayed(), "Save yapıldıktan sonra başarılı bildirimi alınmıyor");
        extentTest.pass("Kullanıcı gizlilik sözleşmesini doldurup save eder");
        extentTest.info("Kullanıcı Terms & Conditions butonuna tıklar.");
        homePage.termsButton.click();
        homePage.termsTextBox.clear();
        homePage.termsTextBox.sendKeys("Şartlar ve koşullar");
        homePage.termsSaveButton.click();
        Assert.assertTrue(homePage.basicBildirim.isDisplayed(), "Save yapıldıktan sonra başarılı bildirimi alınmıyor");
        extentTest.pass("Kullanıcı sözleşmesi basarıyla doldurulup kayıt edildi.");
        extentTest.info("Kullanıcı başarıyla sistemden çıkış yapar");
        homePage.hesapDropDown.click();
        homePage.signOutButtonOK.click();

    }
}
